### ISSUE TITLE
Handle sampling results (tag) in PIP package

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#108]
## Description
After sampling, we get a tag back. Translate the tag into a list of filenames.

## Tasks

- [ ] Update API request to expect a tagId after sampling
- [ ] Add method to translate a tag into a list of related filenames
- [ ] Update methods depending on tags (download dataset, copy dataset) if needed

**Comment by MalteEbner** [comment]
Replaced by https://github.com/lightly-ai/lightly/issues/112
