### ISSUE TITLE
Tutorial: How to use custom augmentations

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#109]
# Tutorial: How to use custom augmentations

## Description
We want to add a tutorial which highlights how a user can use custom augmentations to do self-supervised learning with lightly.

## Tasks
- [x] Find a suitable dataset
- [x] Write the code for the tutorial
- [x] Write the text surrounding the code blocks 
- [x] Add cool plots

## Acceptance Criteria
- [x] Code works and results look meaningful
