### ISSUE TITLE
Update PIP API communication to use the new tag format

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#112]
Depends on https://github.com/lightly-ai/lightly/issues/111

The goal is to make sure the pip package can communicate using the new tag format. 

## Tasks

- [x] The Python client is generated with the new OpenAPI spec.
- [x] The client supports triggering a sampling with the preselected and query tag_id
- [x] The client reads the tag_id from the JobData
- [x] The client gets the tag from the tag_id (via the API)
- [x] The client extracts the sample_ids as bit mask from the tag
- [x] The client extracts the sample_ids as List[int] from the bit mask.
- [x] The client reads the filenames (as List[str]) from the API
- [ ] The client maps the sample_ids to a list of filenames

## Definition of done
- [x] A single test is defined to test all tasks
- [ ] The single tests runs successfully with the updated server
