### ISSUE TITLE
Cleanup benchmark docs

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1204]
## Description

The bechmark docs page is quite outdated and doesn't look very nice. It could do with some love.

https://docs.lightly.ai/self-supervised-learning/getting_started/benchmarks.html

## Tasks

- [ ] Cleanup the benchmark page and make it more appealing
- [ ] Remove outdated/deprecated content
- [ ] Make tables in readme, benchmark scripts, and benchmark docs consistent (epochs, batch size order!)

**Comment by Aienthu1** [comment]
@guarin Can you assign me this issue ?

**Comment by guarin** [comment]
Hey, thanks for your interested on working on this issue. I think this issue is not a good first issue and we'll need some more internal discussions on how to update the benchmarks page.
