### ISSUE TITLE
Cleanup tests

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1206]
## Description

The goal is to:
* Rename test files to match package file structure
* Move all tests to pytest format
* Split subtests into individual tests or use pytest_subtest 
* Move tests for classes into classes and tests for functions into functions. For example:
  ```
  class TestClassName:
      def test_method(self) -> None:
          assert ClassName().method() == something
  
  def test_function() -> None:
      assert module.function() == something
  ```

In this issue we don't care about the api  tests. They are handled in a different project.

For outdated/deprecated modules, such as active learning, we should keep the effort minimal. I would suggest to only make the test filenames match the package file structure. But not change the tests themselves.

## Tasks
- [ ] Cleanup cli tests
- [ ] Cleanup dataset tests
- [ ] Cleanup embedding tests
- [ ] Cleanup loss tests
- [ ] Cleanup models tests
- [ ] Cleanup transforms tests
- [ ] Cleanup utils tests
