### ISSUE TITLE
Update main concepts docs

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1213]
## Description

Update the main concepts page in the docs: https://docs.lightly.ai/self-supervised-learning/getting_started/main_concepts.html

## Tasks

- [ ] Make sure that all major parts of lightly are featured
- [ ] Remove deprecated parts
- [ ] Add paragraph about transforms
- [ ] Update collate paragraph to feature `MultiViewCollate` instead of old collate
- [ ] Can we update the picture at the top to include transforms? Edit: The readme already contains a new picture that includes transforms. Please make sure that this picture is also used in the docs.
