### ISSUE TITLE
Remove prefetch generator

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1214]
## Description

Torch handles prefetching internally and the prefetch generator in PIP is no longer used. We can safely remove it.

## Tasks

- [ ] Remove all code for the prefetch generator
- [ ] Remove dependency for prefetch generator
- [ ] Check if prefetch generator is mentioned in docs
