### ISSUE TITLE
Cleanup setup.py

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1215]
## Tasks

- [ ] Move as many options as possible to setup.cfg
- [ ] Update outdated options (for example Python 10 and 11 are missing in classifiers )
- [ ] Remove unused parts
