### ISSUE TITLE
Move classes and public functions to top of files

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1227]
## Description

* Move classes and exported functions to top of file, move private functions to bottom
* Do this on a per subpackage basis

Private functions or classes start with an underscore:
* `def _private_fun`
* `def _PrivateClass`
* `def public_fun`
* `def PublicClass`

Exceptions are types/type aliases that should remain next to the function/class where they are used.

## Tasks

- [ ] Move public classes and functions to top in lightly/data
- [ ] Move public classes and functions to top in lightly/loss
- [ ] Move public classes and functions to top in lightly/models/modules
- [ ] Move public classes and functions to top in lightly/transforms
- [ ] Move public classes and functions to top in lightly/utils

**Comment by moli-debugger** [comment]
@guarin  I have moved the private func to bottom level for visibility and accessibility. kindly create a seprate issue for moving the private func to the bottom to the mentioned files and assign it to me. 

1. `lightly/models/byol.py`
2. `lightly/models/nnclr.py`
3. `lightly/models/utils.py`

**Comment by guarin** [comment]
@moli-debugger thanks for looking into this! I created the issue here: https://github.com/lightly-ai/lightly/issues/1671 I can assign it to you once you comment on it.

FYI the SSL models in `lightly/models` like `model/simclr.py` etc. are deprecated and will be removed in the next major version update. I'll update the issue description with a list of files that are most important to update.

**Comment by guarin** [comment]
Hi @fadkeabhi, thanks for looking into this! I added some more directories to the issue description. Would you be interested on any of them?

**Comment by fadkeabhi** [comment]
@guarin Thank you for the opportunity. I will work on those directories. Will submit a PR regarding it soon.

**Comment by fadkeabhi** [comment]
@guarin I have submitted a PR for All the above mentioned directories. Take a look at it here https://github.com/lightly-ai/lightly/pull/1685. 
lightly/transforms did not need any changes as it was already cleaned.

**Comment by SauravMaheshkar** [comment]
Closing as completed in #1685
