### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1228]
## Description

@guarin finish writing issue and add subissues

## Tasks

- [ ] Lint the codebase and fix bad mistakes (unused variables, unused imports, …)
- [ ] Add pylint to dev dependencies
- [ ] Do this on a per subpackage basis
- [ ] Check how much effort it would be to enforce linting

**Comment by SSROCKS30** [comment]
Hey @guarin, I have been going to this repository and I am willing to solve this issue. Please can you assign me lightly\data package.

**Comment by SauravMaheshkar** [comment]
Related #1564

**Comment by guarin** [comment]
Let's get ruff merged and then we can start fixing linting errors.

**Comment by RecreationalMath** [comment]
FYI: `ruff` is merged (#1914).

**Comment by Borda** [comment]
@liopeer I guess this can be closed
