### ISSUE TITLE
Cleanup init files

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1229]
## Description

We should go through all the init files in the pip package and make sure we don't import any non-essential modules.

## Tasks

- [ ] Check all init files and make sure they only import important modules
- [ ] Check main init file and figure out if we can drop anything
- [ ] Remove things we don't need anymore
- [ ] Remove or update description at top of main init file
