### ISSUE TITLE
Add support for Torchvision Dataset in MultiViewCollate

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1235]
The `MultiViewCollate` function expects batches as `(image, target, filename)` tuples as returned by the `LightlyDataset`. By making the `filenames` part optional we could also support directly working with torchvision datasets that return only `(image, target)`. This would make Lightly simpler to use and compatible with other dataset implementations.

Note that our transforms are already independent of the `LightlyDataset` so this is the only change required to make `LightlyDataset` fully optional.

## Todo

- [ ] Check [here](https://github.com/lightly-ai/lightly/blob/0ce7315905fc3655af909b5b0fde3fce7989f96d/lightly/data/multi_view_collate.py#L62-L65) if the batch has format `(images, targets, filenames)` or `(images, targets)`. Depending on the batch type, aggregate `filenames` or ignore them.
- [ ] Add test with `MultiViewCollate` and a torchvision dataset
- [ ] Update `MultiViewCollate` docstring

**Comment by guarin** [comment]
Ok, just figured out that the torch [default_collate](https://pytorch.org/docs/stable/data.html#torch.utils.data.default_collate) actually handles batches with multiple views correctly and is compatible with our transforms. So we don't need the `MultiViewCollate` at all!

So I would propose to drop the `MultiViewCollate` from our examples and docs.
