### ISSUE TITLE
Finish I-JEPA

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1320]
Experimental support for I-JEPA was added in #1273 

We should do some refactoring and testing before fully releasing the model.

## Todo

- [ ] Try if we can get it working with timm ViT backbone. I would like to do this because torchvision ViT doesn't support stochastic path dropout, see [comment](https://github.com/lightly-ai/lightly/pull/1273#pullrequestreview-1529960492).
- [ ] Verify that weights are correctly initialized and follow [this](https://github.com/facebookresearch/ijepa/blob/52c1ae95d05f743e000e8f10a1f3a79b10cff048/src/models/vision_transformer.py#L264)
- [ ] Check if we can refactor `IJEPAMaskCollator` into a transform, [comment](https://github.com/lightly-ai/lightly/pull/1273#pullrequestreview-1529960492).
- [ ] Move positional embedding functions (`_get_1d_sincos_pos_embed_from_grid` etc.) to `lightly/models/utils` and add reference to source
- [ ] Add missing docstrings or bring into correct format, check diff from #1273 
- [ ] Add unit tests
- [ ] Finish pytorch lightning and distributed examples
- [ ] Add docs
- [ ] Add imagenet benchmark to `lightly/benchmarks/imagenet/vit/ijepa.py`

**Comment by Natyren** [comment]
Hello @guarin . I can work on it.

**Comment by guarin** [comment]
That would great! Feel free to pick anything up that you are interested in. Let me know if you need help or some clarification.

**Comment by Natyren** [comment]
@guarin 
I will take issues

> * [ ]  Try if we can get it working with timm ViT backbone. I would like to do this because torchvision ViT doesn't support stochastic path dropout, see [comment](https://github.com/lightly-ai/lightly/pull/1273#pullrequestreview-1529960492).
> * [ ]  Verify that weights are correctly initialized and follow [this](https://github.com/facebookresearch/ijepa/blob/52c1ae95d05f743e000e8f10a1f3a79b10cff048/src/models/vision_transformer.py#L264)
> * [ ]  Check if we can refactor `IJEPAMaskCollator` into a transform, [comment](https://github.com/lightly-ai/lightly/pull/1273#pullrequestreview-1529960492).
> * [ ]  Move positional embedding functions (`_get_1d_sincos_pos_embed_from_grid` etc.) to `lightly/models/utils` and add reference to source
> * [ ]  Finish pytorch lightning and distributed examples
> * [ ]  Add docs
> * [ ]  Add imagenet benchmark to `lightly/benchmarks/imagenet/vit/ijepa.py`

Will work on them in next prs

**Comment by Natyren** [comment]
#1322 reference point to this issue
> * [ ]  Move positional embedding functions (`_get_1d_sincos_pos_embed_from_grid` etc.) to `lightly/models/utils` and add reference to source

**Comment by Natyren** [comment]
Next, i will work on implementation of this
> * [ ]  Check if we can refactor `IJEPAMaskCollator` into a transform, [comment](https://github.com/lightly-ai/lightly/pull/1273#pullrequestreview-1529960492).
