### ISSUE TITLE
Create dev-release of pip package

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#143]
## Description
We want to be able to test our pip-package and let it be tested by externals to ensure that many bugs are found. This can be achieved by creating a dev-release

## Tasks
- [ ] Find out how to create a dev release
- [ ] Create the dev release

## Acceptance Criteria
- [ ] The dev-release can be installed easily with `pip install lightly TBD`
- [ ] When installing lightly the normal way with `pip install lightly`, the normal lightly, but NOT the dev release is installed.

## Propsed solution:
Just install directly from a branch with
```
python3 -m pip install git+https://github.com/lightly-ai/lightly.git@develop_active_learning#egg=lightly
```
