### ISSUE TITLE
Release the new pip package

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#144]
## Description
Release the new pip package to be used with the new API

## Dependencies
- #242

## Tasks
- [x] Make sure the staging branch is working
- [ ] Merge staging into master
- [ ] Release the new package on master

## Acceptance Criteria
- [ ] Everyone can use our new pip package after installing it with 'pip install lightly'
