### ISSUE TITLE
[Active learning] Documentation

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#145]
# Documentation for Active Learning

## Description
We need a section on the different concepts used by lightly active learning in our [docs](https://docs.lightly.ai/).
It should be clear, how a user can use lightly to do active learning, what the user needs to bring, and what lightly offers.

## Tasks

- [x] Find a good place in the docs to add a section about active learning.
- [x] Determine what a user needs to know to comfortably use AL with lightly.
- [x] Add the section on active learning to the docs.

## Acceptance Criteria

- [ ] A user can easily find out how to do active learning with lightly through our docs.
