### ISSUE TITLE
Test active learning develop branch

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#147]
# Test Active Learning Branch

## Description
As this branch introduces many breaking changes, we need to make sure that the CLI tools still work. 

## Dependencies
Depends on #149 

## Tasks

- [x] Test lightly-train
- [x] Test lightly-embed
- [x] Test lightly-magic
- [x] Test lightly-upload
- [x] Test lightly-download
- [x] Run tox
- [x] Run end-to-end tests

## Acceptance Criteria

- [x] All tests pass
