### ISSUE TITLE
Switch to using ApiWorkflowClient in CLI

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#149]
# Switch to using ApiWorkflowClient in CLI

**This is not about the endpoints but only about using the new api-client interface!**

This blocks #147.

## Description
The CLI for:
- uploading embeddings (`lightly.cli.upload_cli.py`)
- uploading images (`lightly.cli.upload_cli.py`)
- downloading images (`lightly.cli.download_cli.py`)

still use the old api-client interface. We need to switch to using `ApiWorkflowClient` ASAP to streamline the workflow.

## Tasks

- [x] Fix upload cli for embeddings
- [x] Fix upload cli for images
- [x] Fix download cli
