### ISSUE TITLE
Switch to using OpenApi generated code for image upload

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#150]
# Switch to using OpenApi generated code for image upload

## Description

The upload in `lightly.api.api_workflow_client.py` still uses the old code to upload images. We should switch to using the OpenApi generated endpoints instead.

## Dependencies
- https://github.com/lightly-ai/lightly-core/issues/245
- https://github.com/lightly-ai/lightly-core/issues/267

## Tasks

- [x] Refactor the `upload_dataset` function into a mixin (similar to the `_UploadEmbeddingsMixin`
- [x] Refactor the `upload_dataset` function to use the `openapi_generated` code.
- [x] Refactor the `_upload_single_image` function to use the `openapi_generated` code.
