### ISSUE TITLE
Add FDATransform

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1726]
Add FDATransform based on [Disentangling the Effects of Data Augmentation and Format Transform in Self-Supervised Learning of Image Representations](https://arxiv.org/abs/2312.02205).

The different subtransforms have already been added in https://github.com/lightly-ai/lightly/issues/1646
The goal now is to combine them all into a single FDATransform. Note that the image in the paper shows that the amplitude rescale and phase shift transforms are applied in parallel but we can implement them sequentially as the subtransforms handle the split into amplitude/phase components internally. 

### Tasks

- [ ] Add FDAView1Transform that combines transforms from https://github.com/lightly-ai/lightly/issues/1646
- [ ] Add FDAView2Transform that combines transforms from https://github.com/lightly-ai/lightly/issues/1646
- [ ] Add FDATransform that combines FDAView1Transform and FDAView2Transform

Follow the BYOLTransform code on how to implement the different views and the full FDATransform: https://github.com/lightly-ai/lightly/blob/master/lightly/transforms/byol_transform.py

Each view transform must implement the following steps:
![Screenshot 2024-11-07 at 10 02 15](https://github.com/user-attachments/assets/57d9637a-ee7a-4738-9126-c787c8c202e3)

Parameters for view 1 and 2:
![Screenshot 2024-11-07 at 10 03 00](https://github.com/user-attachments/assets/80b3e39a-1e5d-476e-b13b-30153c0ab320)

**Comment by guarin** [comment]
Thanks for looking into it!

**Comment by vectorvp** [comment]
@guarin, while implementing this I see there is no probability parameters in AmplitudeRescaleTransform and PhaseShiftTransform. Should we add it or what is the workaround?

**Comment by guarin** [comment]
Hi, you can use the `RandomApply` transform from torchvision

**Comment by vectorvp** [comment]
@guarin, please review this [small PR](https://github.com/lightly-ai/lightly/pull/1732). After I will make a PR for the current issue.

**Comment by vectorvp** [comment]
@guarin, hello, please review the PR.
