### ISSUE TITLE
Add checks for newest and minimum required pip version

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#204]
## Dependencies
- https://github.com/lightly-ai/lightly-core/issues/320

## Tasks
- [ ] Reactivate the message in the lightly pip package which tells the user a new pip version is available (see `__init__.py`)
- [ ] Add a check in the `ApiWorkflowClient` which raises an exception if the package is older than allowed.
- [ ] It should be possible to force requests from an older package via env variable, e.g. `LIGHTLY_FORCE_CONNECTION` or similar
