### ISSUE TITLE
EPIC: CLI: streamline handling of dataset_id and filenames for checkpoints and embeddings

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#310]
## Problem:
Currently it is quite cumbersome to do the following steps in order:
```bash
# CLI
lightly-train  # creates checkpoint file
lightly-embed checkpoint=path/to/checkpoint/file/in/some/nested/directory/I/have/to/either/look/up/manually/or/find/where/it/int/the/output/of/the/previous/command # creates embeddings file
lightly-upload embeddings=path/to/embeddings/file/in/some/nested/directory/I/have/to/either/look/up/manually/or/find/where/it/int/the/output/of/the/previous/command
# get the dataset id of the newly created dataset from the webapp and use it for active learning
```
```python
#python
api_client = ApiWorkflowClient(token, dataset_id)
```

Task: Find out how to do this much faster without needing to manually find the filename of the generated files `checkpoint.csv` and `embeddings.csv` or to look up the `dataset_id` in the webapp

## Possible Solutions:
1. allow to set the output file: https://github.com/lightly-ai/lightly/issues/280 (does not solve the `dataset_id` problem)
2. print the `dataset_id` similar to the `output_filename` (https://github.com/lightly-ai/lightly/issues/332) 
3. Mark the `output_filename` and `dataset_id` in a special colour, as proposed in https://github.com/lightly-ai/lightly-core/issues/352
3. save the `output_filename` and `dataset_id` in an environment variable, e.g. LIGHTLY_EMBEDDINGS, LIGHTLY_CHECKPOINT, LIGHTLY_DATASET_ID
4. change the `ApiWorkflowClient(token, dataset_id)` to be able to use the `dataset_name` instead.
6. more solutions?

All 5 solutions are orthogonal to each other and thus they could be combined, but already 1 or 2 of them would solve the problem.
## Definition of done:

- [ ] It is decided how to solve the problem.
- [ ] There is an issue created for this problem.
- [ ] The issues for the other solutions are closed.

**Comment by IgorSusmelj** [comment]
I would do **2** if we create the dataset.

I like **3** if it's not much extra work and does not require extra dependencies. I would do this anyway if there is no extra dependency.

Proposal **4** has the advantage that we can fully script it. I would however rename the env variables:
`LIGHTLY_LAST_EMBEDDING_PATH`, `LIGHTLY_LAST_CHECKPOINT_PATH`, LIGHTLY_LAST_DATASET_ID`
However, if we go with 4 we should use this as the recommended workflow throughout the documentation. 

I would not go for 5 as the dataset name is not unique.

**Comment by philippmwirth** [comment]
I also like 2 & 3 or 4. We could additionally show in the  docs how the output directory can be set to go in the direction of 1.

**Comment by MalteEbner** [comment]
What I like about 4 is that it could make our tutorials much easier, as the user would not need to read the output of the command line and save it somewhere, which would help us for https://github.com/lightly-ai/lightly/issues/350
