### ISSUE TITLE
Adapt active learning score to predict for all and upload to query tag

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#317]
## Description
Following our discussions around #482, we need to change two things to implement B1:
- [x] upload the scores to the query tag
- [x] compute the scores for the whole query tag, not only the unlabeled set
## Tasks
- [x] make the changes in the description
- [x] update the tutorials
- [x] update the documentation

## Acceptance Criteria
- [x] active learning tutorial still works
