### ISSUE TITLE
Add unittests to lightly utils and use them

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#353]
Current the utils do not have unittests, which keeps our coverage low.
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/20324507/117118558-32dadf00-ad91-11eb-81ca-9c6317b4b24b.png">
https://codecov.io/gh/lightly-ai/lightly/tree/c83e55d152140efc991b8e3fcac772e21edd3bb6/lightly/utils

We could add unittests which would increase our coverage a lot.

## Tasks

- [ ] create unittests for benchmarking.py
- [ ] create unittests for embedding_2d.py, alternatively: remove the file or move it to the lightly_utils package as it is used by the worker
- [ ] create unittests for io.py
- [ ] use the reader of the embeddings when sorting before uploading the embeddings https://github.com/lightly-ai/lightly/blob/87426f935f4e8a47baa2fc30b63ffec7d630467c/lightly/api/api_workflow_upload_embeddings.py#L94
- [ ] use the reader of the embeddings in the AL-tutorial with the LogisticRegression classifier https://github.com/lightly-ai/lightly/blob/87426f935f4e8a47baa2fc30b63ffec7d630467c/docs/source/tutorials_source/platform/tutorial_active_learning.py#L132
