### ISSUE TITLE
Automatically set number of workers to number of CPU cores when using the CLI

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#390]
When using the lightly CLI to train and embed models we don't use any workers by default. We decided to go down this road because there were sometimes issues with the PyTorch data loaders when we started working on lightly. However, the system seems quite stable now.

I would suggest switching the default behaviour to use a number of workers = number of CPU cores.

**Todo:**

- [x] Find a simple helper function to determine the number of CPU cores
- [x] Add a new default value for the `loader.num_workers=-1` to automatically find the right number of workers
- [x] Make sure we use the number in
    - [x] `lightly-magic`
    - [x] `lightly-train`
    - [x] `lightly-embed`
    - [x] `lightly-upload`
