### ISSUE TITLE
EPIC: Refactor pip package

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#493]
- [ ] write new momentum encoder (make it more flexible)
- [ ] make cli work 
- [ ] deprecation warning old momentum encoder
- [ ] implement high-level example for one new model (e.g. SwAV) https://github.com/lightly-ai/lightly/issues/492
- [ ] deprecation warnings for old models

- [ ] 3. delete mid-level models in lightly/lightly/models
- [ ] 4. ensure compatibility with old pretrained models
- [ ] 5. update documentation
- [ ] 6. implement high-level examples for all implemented papers based on base building blocks

**Comment by MalteEbner** [comment]
What is still unclear for me is which versions will belong to which steps. We should have clear plans when what will deprecate.

E.g: 
- versions with 1.1.xxxx: Old models work without deprecations warnings
- versions with 1.2.xxxx: New models are working. Old models are still there and working, but raise deprecation warnings. This equals step 1 of this EPIC. We should use the branch `master-refactor-SSL-models` for it.
- versions with 1.3.xxxx The old models are removed. This equals step 2 of the epic. We should use a new branch for it.

**Comment by philippmwirth** [comment]
Requirements for 1.2.0
- Documentation and tutorials are up-to-date (no mid-level models are used)
- Update CLI tool (don't use mid-level models)
- Remove mid-level models

Requirements for 1.3.0
- Refactor datasets and collate functions

**Comment by guarin** [comment]
The cli still uses SelfSupervisedEmbedding objects. We should decide whether we want to continue using it or also change to low level.
